# Generated by Django 6.0.4 on 2026-04-28 19:01

import django.db.models.deletion
import football.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_profile_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('dribbling', 'Dribbling'), ('shooting', 'Shooting'), ('passing', 'Passing'), ('goals', 'Goals'), ('goalkeeper', 'Goalkeeper Saves'), ('freestyle', 'Freestyle'), ('training', 'Training Drills'), ('match', 'Match Highlights')], max_length=50)),
                ('video_file', models.FileField(upload_to='football_videos/', validators=[football.models.validate_video_duration])),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
