# Generated by Django 6.0.4 on 2026-04-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_alter_comment_unique_together_savedvideo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
