# Generated by Django 6.0.4 on 2026-04-29 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_scoutinterest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutinterest',
            name='scout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_interests', to=settings.AUTH_USER_MODEL),
        ),
    ]
