# Generated by Django 6.0.4 on 2026-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_alter_scoutinterest_scout'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scout_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='scout_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='scout_organization',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='scout_region',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_scout',
            field=models.BooleanField(default=False),
        ),
    ]
