# Generated by Django 6.0.4 on 2026-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_reportvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_access_level',
            field=models.CharField(blank=True, default='Full Moderation Access', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_permissions',
            field=models.TextField(blank=True, default='User moderation, video moderation, reports review, verification management, platform protection.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_role',
            field=models.CharField(blank=True, default='Ballconnecthub Platform Administrator', max_length=150),
        ),
    ]
