# Generated by Django 6.0.4 on 2026-05-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_profile_admin_access_level_profile_admin_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('player', 'Player'), ('fan', 'Fan'), ('scout', 'Scout'), ('coach', 'Coach/Club')], default='player', max_length=20),
        ),
    ]
