# Generated by Django 6.0.4 on 2026-05-05 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_alter_profile_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportvideo',
            old_name='reviewed',
            new_name='resolved',
        ),
        migrations.AlterField(
            model_name='reportvideo',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('copyright', 'Copyright'), ('fake', 'Fake Account'), ('violence', 'Violence'), ('abuse', 'Abusive Content'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reportvideo',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
