# Generated by Django 6.0.4 on 2026-05-06 10:48

import cloudinary_storage.storage
import football.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0018_rename_reviewed_reportvideo_resolved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='football_videos/', validators=[football.models.validate_video_duration]),
        ),
    ]
