# Generated by Django 6.0.4 on 2026-05-06 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0019_alter_video_thumbnail_alter_video_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportvideo',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('copyright', 'Copyright'), ('fake', 'Fake Account'), ('violence', 'Violence'), ('abuse', 'Abusive Content'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reportvideo',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
