# Generated by Django 6.0.4 on 2026-05-07 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0020_alter_reportvideo_reason_alter_reportvideo_reporter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['account_type'], name='football_pr_account_c83a43_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country'], name='football_pr_country_04f6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['position'], name='football_pr_positio_d73d42_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['club_or_academy'], name='football_pr_club_or_211b17_idx'),
        ),
        migrations.AddIndex(
            model_name='reportvideo',
            index=models.Index(fields=['created_at'], name='football_re_created_1c45cf_idx'),
        ),
        migrations.AddIndex(
            model_name='reportvideo',
            index=models.Index(fields=['resolved'], name='football_re_resolve_fbfa51_idx'),
        ),
        migrations.AddIndex(
            model_name='reportvideo',
            index=models.Index(fields=['reason'], name='football_re_reason_def211_idx'),
        ),
        migrations.AddIndex(
            model_name='reportvideo',
            index=models.Index(fields=['video'], name='football_re_video_i_e265cb_idx'),
        ),
        migrations.AddIndex(
            model_name='reportvideo',
            index=models.Index(fields=['reporter'], name='football_re_reporte_76f2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['created_at'], name='football_vi_created_218c66_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category'], name='football_vi_categor_2150fd_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['views'], name='football_vi_views_c07104_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['player'], name='football_vi_player__f63141_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title'], name='football_vi_title_efd7a7_idx'),
        ),
    ]
